version: '3.8'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./identities:/app/identities
      - ./tweets:/app/tweets
    env_file:
      - .env
    restart: unless-stopped
    # entrypoint: npm run start
    entrypoint: npm run start:no-build
    
